/** Declaration file generated by dts-gen */

declare module 'grommet-theme-v1' {
  export = grommet_theme_v1;

  declare const grommet_theme_v1: {
    v1: {
      button: {
        extend: string[];
      };
      checkBox: {
        icon: {
          extend: string[];
        };
      };
      global: {
        colors: {
          'accent-1': string;
          'accent-2': string;
          background: string;
          border: string;
          brand: string;
          control: string;
          'dark-1': string;
          'dark-2': string;
          'dark-3': string;
          'dark-4': string;
          'dark-6': string;
          focus: string;
          'light-1': string;
          'neutral-1': string;
          'neutral-2': string;
          'neutral-3': string;
          'status-critical': string;
          'status-disabled': string;
          'status-ok': string;
          'status-unknown': string;
          'status-warning': string;
        };
        control: {
          border: {
            color: string;
            radius: string;
            width: string;
          };
        };
        font: {
          face: string;
          family: string;
        };
      };
    };
  };
}
