/** Declaration file generated by dts-gen */

export const base: {
    global: {
        colors: {
            icon: string;
        };
    };
    icon: {
        size: {
            large: string;
            medium: string;
            small: string;
            xlarge: string;
        };
    };
};

export const defaultProps: {
    theme: {
        global: {
            colors: {
                icon: string;
            };
        };
        icon: {
            size: {
                large: string;
                medium: string;
                small: string;
                xlarge: string;
            };
        };
    };
};

export function Accessibility(props: any): any;

export function Achievement(props: any): any;

export function Action(props: any): any;

export function Actions(props: any): any;

export function Ad(props: any): any;

export function Add(props: any): any;

export function AddCircle(props: any): any;

export function Aed(props: any): any;

export function Aggregate(props: any): any;

export function Aid(props: any): any;

export function AidOption(props: any): any;

export function Alarm(props: any): any;

export function Alert(props: any): any;

export function Amazon(props: any): any;

export function Amex(props: any): any;

export function Analytics(props: any): any;

export function Anchor(props: any): any;

export function Android(props: any): any;

export function Announce(props: any): any;

export function Apple(props: any): any;

export function Apps(props: any): any;

export function Archive(props: any): any;

export function Archlinux(props: any): any;

export function Article(props: any): any;

export function Aruba(props: any): any;

export function Ascend(props: any): any;

export function AssistListening(props: any): any;

export function Atm(props: any): any;

export function Attachment(props: any): any;

export function Attraction(props: any): any;

export function Baby(props: any): any;

export function BackTen(props: any): any;

export function Bar(props: any): any;

export function BarChart(props: any): any;

export function Basket(props: any): any;

export function Bike(props: any): any;

export function Bitcoin(props: any): any;

export function Blank(props: any): any;

export function BlockQuote(props: any): any;

export function Blog(props: any): any;

export function Bluetooth(props: any): any;

export function Bold(props: any): any;

export function Book(props: any): any;

export function Bookmark(props: any): any;

export function BottomCorner(props: any): any;

export function Braille(props: any): any;

export function Briefcase(props: any): any;

export function Brush(props: any): any;

export function Bug(props: any): any;

export function Bundle(props: any): any;

export function Bus(props: any): any;

export function BusinessService(props: any): any;

export function Cafeteria(props: any): any;

export function Calculator(props: any): any;

export function Calendar(props: any): any;

export function Camera(props: any): any;

export function Capacity(props: any): any;

export function Car(props: any): any;

export function CaretDown(props: any): any;

export function CaretNext(props: any): any;

export function CaretPrevious(props: any): any;

export function CaretUp(props: any): any;

export function Cart(props: any): any;

export function Catalog(props: any): any;

export function CatalogOption(props: any): any;

export function Centos(props: any): any;

export function Channel(props: any): any;

export function ChapterAdd(props: any): any;

export function ChapterNext(props: any): any;

export function ChapterPrevious(props: any): any;

export function Chat(props: any): any;

export function ChatOption(props: any): any;

export function Checkbox(props: any): any;

export function CheckboxSelected(props: any): any;

export function Checkmark(props: any): any;

export function Chrome(props: any): any;

export function CircleInformation(props: any): any;

export function CirclePlay(props: any): any;

export function CircleQuestion(props: any): any;

export function Clear(props: any): any;

export function ClearOption(props: any): any;

export function Cli(props: any): any;

export function Clipboard(props: any): any;

export function Clock(props: any): any;

export function Clone(props: any): any;

export function Close(props: any): any;

export function ClosedCaption(props: any): any;

export function Cloud(props: any): any;

export function CloudComputer(props: any): any;

export function CloudDownload(props: any): any;

export function CloudSoftware(props: any): any;

export function CloudUpload(props: any): any;

export function Cloudlinux(props: any): any;

export function Cluster(props: any): any;

export function CoatCheck(props: any): any;

export function Code(props: any): any;

export function CodeSandbox(props: any): any;

export function Codepen(props: any): any;

export function Columns(props: any): any;

export function Command(props: any): any;

export function Compare(props: any): any;

export function Compass(props: any): any;

export function Compliance(props: any): any;

export function Configure(props: any): any;

export function Connect(props: any): any;

export function Connectivity(props: any): any;

export function Contact(props: any): any;

export function ContactInfo(props: any): any;

export function Contract(props: any): any;

export function Copy(props: any): any;

export function CreativeCommons(props: any): any;

export function CreditCard(props: any): any;

export function Css3(props: any): any;

export function Cube(props: any): any;

export function Cubes(props: any): any;

export function Currency(props: any): any;

export function Cursor(props: any): any;

export function Cut(props: any): any;

export function Cycle(props: any): any;

export function Dashboard(props: any): any;

export function Database(props: any): any;

export function Debian(props: any): any;

export function Deliver(props: any): any;

export function Deploy(props: any): any;

export function Descend(props: any): any;

export function Desktop(props: any): any;

export function Detach(props: any): any;

export function Device(props: any): any;

export function Diamond(props: any): any;

export function Directions(props: any): any;

export function Disc(props: any): any;

export function Dislike(props: any): any;

export function Docker(props: any): any;

export function Document(props: any): any;

export function DocumentCloud(props: any): any;

export function DocumentConfig(props: any): any;

export function DocumentCsv(props: any): any;

export function DocumentDownload(props: any): any;

export function DocumentExcel(props: any): any;

export function DocumentImage(props: any): any;

export function DocumentLocked(props: any): any;

export function DocumentMissing(props: any): any;

export function DocumentNotes(props: any): any;

export function DocumentOutlook(props: any): any;

export function DocumentPdf(props: any): any;

export function DocumentPerformance(props: any): any;

export function DocumentPpt(props: any): any;

export function DocumentRtf(props: any): any;

export function DocumentSound(props: any): any;

export function DocumentStore(props: any): any;

export function DocumentTest(props: any): any;

export function DocumentText(props: any): any;

export function DocumentThreat(props: any): any;

export function DocumentTime(props: any): any;

export function DocumentTransfer(props: any): any;

export function DocumentTxt(props: any): any;

export function DocumentUpdate(props: any): any;

export function DocumentUpload(props: any): any;

export function DocumentUser(props: any): any;

export function DocumentVerified(props: any): any;

export function DocumentVideo(props: any): any;

export function DocumentWindows(props: any): any;

export function DocumentWord(props: any): any;

export function DocumentZip(props: any): any;

export function Domain(props: any): any;

export function Dos(props: any): any;

export function Down(props: any): any;

export function Download(props: any): any;

export function Drag(props: any): any;

export function Drawer(props: any): any;

export function DriveCage(props: any): any;

export function Dropbox(props: any): any;

export function Duplicate(props: any): any;

export function Dxc(props: any): any;

export function Edge(props: any): any;

export function Edit(props: any): any;

export function Eject(props: any): any;

export function Elevator(props: any): any;

export function Emergency(props: any): any;

export function Emoji(props: any): any;

export function EmptyCircle(props: any): any;

export function Erase(props: any): any;

export function Escalator(props: any): any;

export function Expand(props: any): any;

export function Facebook(props: any): any;

export function FacebookOption(props: any): any;

export function Fan(props: any): any;

export function FastForward(props: any): any;

export function Favorite(props: any): any;

export function Fedora(props: any): any;

export function Filter(props: any): any;

export function FingerPrint(props: any): any;

export function Fireball(props: any): any;

export function Firefox(props: any): any;

export function Flag(props: any): any;

export function FlagFill(props: any): any;

export function Folder(props: any): any;

export function FolderCycle(props: any): any;

export function FolderOpen(props: any): any;

export function FormAdd(props: any): any;

export function FormAttachment(props: any): any;

export function FormCalendar(props: any): any;

export function FormCheckmark(props: any): any;

export function FormClock(props: any): any;

export function FormClose(props: any): any;

export function FormCut(props: any): any;

export function FormDown(props: any): any;

export function FormEdit(props: any): any;

export function FormFilter(props: any): any;

export function FormFolder(props: any): any;

export function FormLocation(props: any): any;

export function FormLock(props: any): any;

export function FormNext(props: any): any;

export function FormNextLink(props: any): any;

export function FormPrevious(props: any): any;

export function FormPreviousLink(props: any): any;

export function FormRefresh(props: any): any;

export function FormSchedule(props: any): any;

export function FormSearch(props: any): any;

export function FormSubtract(props: any): any;

export function FormTrash(props: any): any;

export function FormUp(props: any): any;

export function FormUpload(props: any): any;

export function FormView(props: any): any;

export function FormViewHide(props: any): any;

export function ForwardTen(props: any): any;

export function Freebsd(props: any): any;

export function Gallery(props: any): any;

export function Gamepad(props: any): any;

export function Gift(props: any): any;

export function Github(props: any): any;

export function Globe(props: any): any;

export function Golang(props: any): any;

export function Google(props: any): any;

export function GooglePlus(props: any): any;

export function GoogleWallet(props: any): any;

export function Gremlin(props: any): any;

export function Grid(props: any): any;

export function Grommet(props: any): any;

export function Group(props: any): any;

export function Grow(props: any): any;

export function Hadoop(props: any): any;

export function Halt(props: any): any;

export function Help(props: any): any;

export function Heroku(props: any): any;

export function History(props: any): any;

export function Home(props: any): any;

export function Horton(props: any): any;

export function Host(props: any): any;

export function HostMaintenance(props: any): any;

export function Hp(props: any): any;

export function Hpe(props: any): any;

export function HpeLabs(props: any): any;

export function Hpi(props: any): any;

export function Html5(props: any): any;

export function IceCream(props: any): any;

export function Image(props: any): any;

export function Impact(props: any): any;

export function InProgress(props: any): any;

export function Inbox(props: any): any;

export function Indicator(props: any): any;

export function Info(props: any): any;

export function Inherit(props: any): any;

export function Inspect(props: any): any;

export function Instagram(props: any): any;

export function Install(props: any): any;

export function InstallOption(props: any): any;

export function Integration(props: any): any;

export function InternetExplorer(props: any): any;

export function Italic(props: any): any;

export function Iteration(props: any): any;

export function Java(props: any): any;

export function Keyboard(props: any): any;

export function Language(props: any): any;

export function Launch(props: any): any;

export function Layer(props: any): any;

export function License(props: any): any;

export function Like(props: any): any;

export function LineChart(props: any): any;

export function Link(props: any): any;

export function LinkBottom(props: any): any;

export function LinkDown(props: any): any;

export function LinkNext(props: any): any;

export function LinkPrevious(props: any): any;

export function LinkTop(props: any): any;

export function LinkUp(props: any): any;

export function Linkedin(props: any): any;

export function LinkedinOption(props: any): any;

export function Local(props: any): any;

export function Location(props: any): any;

export function LocationPin(props: any): any;

export function Lock(props: any): any;

export function Login(props: any): any;

export function Logout(props: any): any;

export function Lounge(props: any): any;

export function Magic(props: any): any;

export function Mail(props: any): any;

export function MailOption(props: any): any;

export function Mandriva(props: any): any;

export function Manual(props: any): any;

export function Map(props: any): any;

export function MapLocation(props: any): any;

export function Mastercard(props: any): any;

export function Medium(props: any): any;

export function Menu(props: any): any;

export function Microfocus(props: any): any;

export function Microphone(props: any): any;

export function Money(props: any): any;

export function Monitor(props: any): any;

export function Monospace(props: any): any;

export function More(props: any): any;

export function Multimedia(props: any): any;

export function Multiple(props: any): any;

export function Music(props: any): any;

export function Mysql(props: any): any;

export function Navigate(props: any): any;

export function Network(props: any): any;

export function New(props: any): any;

export function NewWindow(props: any): any;

export function Next(props: any): any;

export function Nodes(props: any): any;

export function Norton(props: any): any;

export function Note(props: any): any;

export function Notes(props: any): any;

export function Notification(props: any): any;

export function ObjectGroup(props: any): any;

export function ObjectUngroup(props: any): any;

export function OfflineStorage(props: any): any;

export function Onedrive(props: any): any;

export function Opera(props: any): any;

export function Optimize(props: any): any;

export function Oracle(props: any): any;

export function OrderedList(props: any): any;

export function Organization(props: any): any;

export function Overview(props: any): any;

export function Paint(props: any): any;

export function Pan(props: any): any;

export function Pause(props: any): any;

export function PauseFill(props: any): any;

export function Paypal(props: any): any;

export function Performance(props: any): any;

export function PersonalComputer(props: any): any;

export function PieChart(props: any): any;

export function PiedPiper(props: any): any;

export function Pin(props: any): any;

export function Pinterest(props: any): any;

export function Plan(props: any): any;

export function Play(props: any): any;

export function PlayFill(props: any): any;

export function Power(props: any): any;

export function PowerCycle(props: any): any;

export function PowerForceShutdown(props: any): any;

export function PowerReset(props: any): any;

export function PowerShutdown(props: any): any;

export function Previous(props: any): any;

export function Print(props: any): any;

export function ProductHunt(props: any): any;

export function Projects(props: any): any;

export function Radial(props: any): any;

export function RadialSelected(props: any): any;

export function Raspberry(props: any): any;

export function Reactjs(props: any): any;

export function Reddit(props: any): any;

export function Redhat(props: any): any;

export function Redo(props: any): any;

export function Refresh(props: any): any;

export function Resources(props: any): any;

export function Restaurant(props: any): any;

export function Restroom(props: any): any;

export function RestroomMen(props: any): any;

export function RestroomWomen(props: any): any;

export function Resume(props: any): any;

export function Return(props: any): any;

export function Revert(props: any): any;

export function Rewind(props: any): any;

export function Risk(props: any): any;

export function Robot(props: any): any;

export function RotateLeft(props: any): any;

export function RotateRight(props: any): any;

export function Rss(props: any): any;

export function Run(props: any): any;

export function SafariOption(props: any): any;

export function Satellite(props: any): any;

export function Save(props: any): any;

export function Scan(props: any): any;

export function Schedule(props: any): any;

export function ScheduleNew(props: any): any;

export function SchedulePlay(props: any): any;

export function Schedules(props: any): any;

export function Sco(props: any): any;

export function Scorecard(props: any): any;

export function Search(props: any): any;

export function SearchAdvanced(props: any): any;

export function Secure(props: any): any;

export function Select(props: any): any;

export function Selection(props: any): any;

export function Semantics(props: any): any;

export function Send(props: any): any;

export function Server(props: any): any;

export function ServerCluster(props: any): any;

export function Servers(props: any): any;

export function ServicePlay(props: any): any;

export function Services(props: any): any;

export function SettingsOption(props: any): any;

export function Share(props: any): any;

export function ShareOption(props: any): any;

export function Shield(props: any): any;

export function ShieldSecurity(props: any): any;

export function Shift(props: any): any;

export function Shop(props: any): any;

export function Sidebar(props: any): any;

export function Sign(props: any): any;

export function Skype(props: any): any;

export function Slack(props: any): any;

export function Snapchat(props: any): any;

export function Solaris(props: any): any;

export function Sort(props: any): any;

export function Spa(props: any): any;

export function Split(props: any): any;

export function Splits(props: any): any;

export function Square(props: any): any;

export function StackOverflow(props: any): any;

export function Stakeholder(props: any): any;

export function Star(props: any): any;

export function StarHalf(props: any): any;

export function StatusCritical(props: any): any;

export function StatusCriticalSmall(props: any): any;

export function StatusDisabled(props: any): any;

export function StatusDisabledSmall(props: any): any;

export function StatusGood(props: any): any;

export function StatusGoodSmall(props: any): any;

export function StatusInfo(props: any): any;

export function StatusInfoSmall(props: any): any;

export function StatusPlaceholder(props: any): any;

export function StatusPlaceholderSmall(props: any): any;

export function StatusUnknown(props: any): any;

export function StatusUnknownSmall(props: any): any;

export function StatusWarning(props: any): any;

export function StatusWarningSmall(props: any): any;

export function Steps(props: any): any;

export function StepsOption(props: any): any;

export function Stop(props: any): any;

export function StopFill(props: any): any;

export function Storage(props: any): any;

export function StreetView(props: any): any;

export function StrikeThrough(props: any): any;

export function Stripe(props: any): any;

export function Subscript(props: any): any;

export function Subtract(props: any): any;

export function SubtractCircle(props: any): any;

export function Superscript(props: any): any;

export function Support(props: any): any;

export function Suse(props: any): any;

export function Swift(props: any): any;

export function Swim(props: any): any;

export function Sync(props: any): any;

export function System(props: any): any;

export function Table(props: any): any;

export function TableAdd(props: any): any;

export function Tag(props: any): any;

export function Tape(props: any): any;

export function TapeOption(props: any): any;

export function Target(props: any): any;

export function Task(props: any): any;

export function Tasks(props: any): any;

export function Technology(props: any): any;

export function Template(props: any): any;

export function Terminal(props: any): any;

export function Test(props: any): any;

export function TestDesktop(props: any): any;

export function TextAlignCenter(props: any): any;

export function TextAlignFull(props: any): any;

export function TextAlignLeft(props: any): any;

export function TextAlignRight(props: any): any;

export function TextWrap(props: any): any;

export function Threats(props: any): any;

export function ThreeD(props: any): any;

export function ThreeDffects(props: any): any;

export function Ticket(props: any): any;

export function Tip(props: any): any;

export function Toast(props: any): any;

export function Tools(props: any): any;

export function Tooltip(props: any): any;

export function TopCorner(props: any): any;

export function Train(props: any): any;

export function Transaction(props: any): any;

export function Trash(props: any): any;

export function Tree(props: any): any;

export function TreeOption(props: any): any;

export function Trigger(props: any): any;

export function Trophy(props: any): any;

export function Troubleshoot(props: any): any;

export function Tty(props: any): any;

export function Tumblr(props: any): any;

export function Turbolinux(props: any): any;

export function Twitter(props: any): any;

export function Ubuntu(props: any): any;

export function Underline(props: any): any;

export function Undo(props: any): any;

export function Unlink(props: any): any;

export function Unlock(props: any): any;

export function UnorderedList(props: any): any;

export function Up(props: any): any;

export function Update(props: any): any;

export function Upgrade(props: any): any;

export function Upload(props: any): any;

export function User(props: any): any;

export function UserAdd(props: any): any;

export function UserAdmin(props: any): any;

export function UserExpert(props: any): any;

export function UserFemale(props: any): any;

export function UserManager(props: any): any;

export function UserNew(props: any): any;

export function UserPolice(props: any): any;

export function UserSettings(props: any): any;

export function UserWorker(props: any): any;

export function Validate(props: any): any;

export function Vend(props: any): any;

export function Video(props: any): any;

export function View(props: any): any;

export function Vimeo(props: any): any;

export function VirtualMachine(props: any): any;

export function VirtualStorage(props: any): any;

export function Visa(props: any): any;

export function VmMaintenance(props: any): any;

export function Vmware(props: any): any;

export function Volume(props: any): any;

export function VolumeControl(props: any): any;

export function VolumeLow(props: any): any;

export function VolumeMute(props: any): any;

export function Vulnerability(props: any): any;

export function Waypoint(props: any): any;

export function Wheelchair(props: any): any;

export function WheelchairActive(props: any): any;

export function Wifi(props: any): any;

export function WifiLow(props: any): any;

export function WifiMedium(props: any): any;

export function WifiNone(props: any): any;

export function Windows(props: any): any;

export function WindowsLegacy(props: any): any;

export function Wordpress(props: any): any;

export function Workshop(props: any): any;

export function Yoga(props: any): any;

export function Youtube(props: any): any;

export function ZoomIn(props: any): any;

export function ZoomOut(props: any): any;

export function extendDefaultTheme(theme: any): void;

export namespace Accessibility {
    const prototype: {
    };

}

export namespace Achievement {
    const prototype: {
    };

}

export namespace Action {
    const prototype: {
    };

}

export namespace Actions {
    const prototype: {
    };

}

export namespace Ad {
    const prototype: {
    };

}

export namespace Add {
    const prototype: {
    };

}

export namespace AddCircle {
    const prototype: {
    };

}

export namespace Aed {
    const prototype: {
    };

}

export namespace Aggregate {
    const prototype: {
    };

}

export namespace Aid {
    const prototype: {
    };

}

export namespace AidOption {
    const prototype: {
    };

}

export namespace Alarm {
    const prototype: {
    };

}

export namespace Alert {
    const prototype: {
    };

}

export namespace Amazon {
    const prototype: {
    };

}

export namespace Amex {
    const prototype: {
    };

}

export namespace Analytics {
    const prototype: {
    };

}

export namespace Anchor {
    const prototype: {
    };

}

export namespace Android {
    const prototype: {
    };

}

export namespace Announce {
    const prototype: {
    };

}

export namespace Apple {
    const prototype: {
    };

}

export namespace Apps {
    const prototype: {
    };

}

export namespace Archive {
    const prototype: {
    };

}

export namespace Archlinux {
    const prototype: {
    };

}

export namespace Article {
    const prototype: {
    };

}

export namespace Aruba {
    const prototype: {
    };

}

export namespace Ascend {
    const prototype: {
    };

}

export namespace AssistListening {
    const prototype: {
    };

}

export namespace Atm {
    const prototype: {
    };

}

export namespace Attachment {
    const prototype: {
    };

}

export namespace Attraction {
    const prototype: {
    };

}

export namespace Baby {
    const prototype: {
    };

}

export namespace BackTen {
    const prototype: {
    };

}

export namespace Bar {
    const prototype: {
    };

}

export namespace BarChart {
    const prototype: {
    };

}

export namespace Basket {
    const prototype: {
    };

}

export namespace Bike {
    const prototype: {
    };

}

export namespace Bitcoin {
    const prototype: {
    };

}

export namespace Blank {
    const prototype: {
    };

}

export namespace BlockQuote {
    const prototype: {
    };

}

export namespace Blog {
    const prototype: {
    };

}

export namespace Bluetooth {
    const prototype: {
    };

}

export namespace Bold {
    const prototype: {
    };

}

export namespace Book {
    const prototype: {
    };

}

export namespace Bookmark {
    const prototype: {
    };

}

export namespace BottomCorner {
    const prototype: {
    };

}

export namespace Braille {
    const prototype: {
    };

}

export namespace Briefcase {
    const prototype: {
    };

}

export namespace Brush {
    const prototype: {
    };

}

export namespace Bug {
    const prototype: {
    };

}

export namespace Bundle {
    const prototype: {
    };

}

export namespace Bus {
    const prototype: {
    };

}

export namespace BusinessService {
    const prototype: {
    };

}

export namespace Cafeteria {
    const prototype: {
    };

}

export namespace Calculator {
    const prototype: {
    };

}

export namespace Calendar {
    const prototype: {
    };

}

export namespace Camera {
    const prototype: {
    };

}

export namespace Capacity {
    const prototype: {
    };

}

export namespace Car {
    const prototype: {
    };

}

export namespace CaretDown {
    const prototype: {
    };

}

export namespace CaretNext {
    const prototype: {
    };

}

export namespace CaretPrevious {
    const prototype: {
    };

}

export namespace CaretUp {
    const prototype: {
    };

}

export namespace Cart {
    const prototype: {
    };

}

export namespace Catalog {
    const prototype: {
    };

}

export namespace CatalogOption {
    const prototype: {
    };

}

export namespace Centos {
    const prototype: {
    };

}

export namespace Channel {
    const prototype: {
    };

}

export namespace ChapterAdd {
    const prototype: {
    };

}

export namespace ChapterNext {
    const prototype: {
    };

}

export namespace ChapterPrevious {
    const prototype: {
    };

}

export namespace Chat {
    const prototype: {
    };

}

export namespace ChatOption {
    const prototype: {
    };

}

export namespace Checkbox {
    const prototype: {
    };

}

export namespace CheckboxSelected {
    const prototype: {
    };

}

export namespace Checkmark {
    const prototype: {
    };

}

export namespace Chrome {
    const prototype: {
    };

}

export namespace CircleInformation {
    const prototype: {
    };

}

export namespace CirclePlay {
    const prototype: {
    };

}

export namespace CircleQuestion {
    const prototype: {
    };

}

export namespace Clear {
    const prototype: {
    };

}

export namespace ClearOption {
    const prototype: {
    };

}

export namespace Cli {
    const prototype: {
    };

}

export namespace Clipboard {
    const prototype: {
    };

}

export namespace Clock {
    const prototype: {
    };

}

export namespace Clone {
    const prototype: {
    };

}

export namespace Close {
    const prototype: {
    };

}

export namespace ClosedCaption {
    const prototype: {
    };

}

export namespace Cloud {
    const prototype: {
    };

}

export namespace CloudComputer {
    const prototype: {
    };

}

export namespace CloudDownload {
    const prototype: {
    };

}

export namespace CloudSoftware {
    const prototype: {
    };

}

export namespace CloudUpload {
    const prototype: {
    };

}

export namespace Cloudlinux {
    const prototype: {
    };

}

export namespace Cluster {
    const prototype: {
    };

}

export namespace CoatCheck {
    const prototype: {
    };

}

export namespace Code {
    const prototype: {
    };

}

export namespace CodeSandbox {
    const prototype: {
    };

}

export namespace Codepen {
    const prototype: {
    };

}

export namespace Columns {
    const prototype: {
    };

}

export namespace Command {
    const prototype: {
    };

}

export namespace Compare {
    const prototype: {
    };

}

export namespace Compass {
    const prototype: {
    };

}

export namespace Compliance {
    const prototype: {
    };

}

export namespace Configure {
    const prototype: {
    };

}

export namespace Connect {
    const prototype: {
    };

}

export namespace Connectivity {
    const prototype: {
    };

}

export namespace Contact {
    const prototype: {
    };

}

export namespace ContactInfo {
    const prototype: {
    };

}

export namespace Contract {
    const prototype: {
    };

}

export namespace Copy {
    const prototype: {
    };

}

export namespace CreativeCommons {
    const prototype: {
    };

}

export namespace CreditCard {
    const prototype: {
    };

}

export namespace Css3 {
    const prototype: {
    };

}

export namespace Cube {
    const prototype: {
    };

}

export namespace Cubes {
    const prototype: {
    };

}

export namespace Currency {
    const prototype: {
    };

}

export namespace Cursor {
    const prototype: {
    };

}

export namespace Cut {
    const prototype: {
    };

}

export namespace Cycle {
    const prototype: {
    };

}

export namespace Dashboard {
    const prototype: {
    };

}

export namespace Database {
    const prototype: {
    };

}

export namespace Debian {
    const prototype: {
    };

}

export namespace Deliver {
    const prototype: {
    };

}

export namespace Deploy {
    const prototype: {
    };

}

export namespace Descend {
    const prototype: {
    };

}

export namespace Desktop {
    const prototype: {
    };

}

export namespace Detach {
    const prototype: {
    };

}

export namespace Device {
    const prototype: {
    };

}

export namespace Diamond {
    const prototype: {
    };

}

export namespace Directions {
    const prototype: {
    };

}

export namespace Disc {
    const prototype: {
    };

}

export namespace Dislike {
    const prototype: {
    };

}

export namespace Docker {
    const prototype: {
    };

}

export namespace Document {
    const prototype: {
    };

}

export namespace DocumentCloud {
    const prototype: {
    };

}

export namespace DocumentConfig {
    const prototype: {
    };

}

export namespace DocumentCsv {
    const prototype: {
    };

}

export namespace DocumentDownload {
    const prototype: {
    };

}

export namespace DocumentExcel {
    const prototype: {
    };

}

export namespace DocumentImage {
    const prototype: {
    };

}

export namespace DocumentLocked {
    const prototype: {
    };

}

export namespace DocumentMissing {
    const prototype: {
    };

}

export namespace DocumentNotes {
    const prototype: {
    };

}

export namespace DocumentOutlook {
    const prototype: {
    };

}

export namespace DocumentPdf {
    const prototype: {
    };

}

export namespace DocumentPerformance {
    const prototype: {
    };

}

export namespace DocumentPpt {
    const prototype: {
    };

}

export namespace DocumentRtf {
    const prototype: {
    };

}

export namespace DocumentSound {
    const prototype: {
    };

}

export namespace DocumentStore {
    const prototype: {
    };

}

export namespace DocumentTest {
    const prototype: {
    };

}

export namespace DocumentText {
    const prototype: {
    };

}

export namespace DocumentThreat {
    const prototype: {
    };

}

export namespace DocumentTime {
    const prototype: {
    };

}

export namespace DocumentTransfer {
    const prototype: {
    };

}

export namespace DocumentTxt {
    const prototype: {
    };

}

export namespace DocumentUpdate {
    const prototype: {
    };

}

export namespace DocumentUpload {
    const prototype: {
    };

}

export namespace DocumentUser {
    const prototype: {
    };

}

export namespace DocumentVerified {
    const prototype: {
    };

}

export namespace DocumentVideo {
    const prototype: {
    };

}

export namespace DocumentWindows {
    const prototype: {
    };

}

export namespace DocumentWord {
    const prototype: {
    };

}

export namespace DocumentZip {
    const prototype: {
    };

}

export namespace Domain {
    const prototype: {
    };

}

export namespace Dos {
    const prototype: {
    };

}

export namespace Down {
    const prototype: {
    };

}

export namespace Download {
    const prototype: {
    };

}

export namespace Drag {
    const prototype: {
    };

}

export namespace Drawer {
    const prototype: {
    };

}

export namespace DriveCage {
    const prototype: {
    };

}

export namespace Dropbox {
    const prototype: {
    };

}

export namespace Duplicate {
    const prototype: {
    };

}

export namespace Dxc {
    const prototype: {
    };

}

export namespace Edge {
    const prototype: {
    };

}

export namespace Edit {
    const prototype: {
    };

}

export namespace Eject {
    const prototype: {
    };

}

export namespace Elevator {
    const prototype: {
    };

}

export namespace Emergency {
    const prototype: {
    };

}

export namespace Emoji {
    const prototype: {
    };

}

export namespace EmptyCircle {
    const prototype: {
    };

}

export namespace Erase {
    const prototype: {
    };

}

export namespace Escalator {
    const prototype: {
    };

}

export namespace Expand {
    const prototype: {
    };

}

export namespace Facebook {
    const prototype: {
    };

}

export namespace FacebookOption {
    const prototype: {
    };

}

export namespace Fan {
    const prototype: {
    };

}

export namespace FastForward {
    const prototype: {
    };

}

export namespace Favorite {
    const prototype: {
    };

}

export namespace Fedora {
    const prototype: {
    };

}

export namespace Filter {
    const prototype: {
    };

}

export namespace FingerPrint {
    const prototype: {
    };

}

export namespace Fireball {
    const prototype: {
    };

}

export namespace Firefox {
    const prototype: {
    };

}

export namespace Flag {
    const prototype: {
    };

}

export namespace FlagFill {
    const prototype: {
    };

}

export namespace Folder {
    const prototype: {
    };

}

export namespace FolderCycle {
    const prototype: {
    };

}

export namespace FolderOpen {
    const prototype: {
    };

}

export namespace FormAdd {
    const prototype: {
    };

}

export namespace FormAttachment {
    const prototype: {
    };

}

export namespace FormCalendar {
    const prototype: {
    };

}

export namespace FormCheckmark {
    const prototype: {
    };

}

export namespace FormClock {
    const prototype: {
    };

}

export namespace FormClose {
    const prototype: {
    };

}

export namespace FormCut {
    const prototype: {
    };

}

export namespace FormDown {
    const prototype: {
    };

}

export namespace FormEdit {
    const prototype: {
    };

}

export namespace FormFilter {
    const prototype: {
    };

}

export namespace FormFolder {
    const prototype: {
    };

}

export namespace FormLocation {
    const prototype: {
    };

}

export namespace FormLock {
    const prototype: {
    };

}

export namespace FormNext {
    const prototype: {
    };

}

export namespace FormNextLink {
    const prototype: {
    };

}

export namespace FormPrevious {
    const prototype: {
    };

}

export namespace FormPreviousLink {
    const prototype: {
    };

}

export namespace FormRefresh {
    const prototype: {
    };

}

export namespace FormSchedule {
    const prototype: {
    };

}

export namespace FormSearch {
    const prototype: {
    };

}

export namespace FormSubtract {
    const prototype: {
    };

}

export namespace FormTrash {
    const prototype: {
    };

}

export namespace FormUp {
    const prototype: {
    };

}

export namespace FormUpload {
    const prototype: {
    };

}

export namespace FormView {
    const prototype: {
    };

}

export namespace FormViewHide {
    const prototype: {
    };

}

export namespace ForwardTen {
    const prototype: {
    };

}

export namespace Freebsd {
    const prototype: {
    };

}

export namespace Gallery {
    const prototype: {
    };

}

export namespace Gamepad {
    const prototype: {
    };

}

export namespace Gift {
    const prototype: {
    };

}

export namespace Github {
    const prototype: {
    };

}

export namespace Globe {
    const prototype: {
    };

}

export namespace Golang {
    const prototype: {
    };

}

export namespace Google {
    const prototype: {
    };

}

export namespace GooglePlus {
    const prototype: {
    };

}

export namespace GoogleWallet {
    const prototype: {
    };

}

export namespace Gremlin {
    const prototype: {
    };

}

export namespace Grid {
    const prototype: {
    };

}

export namespace Grommet {
    const prototype: {
    };

}

export namespace Group {
    const prototype: {
    };

}

export namespace Grow {
    const prototype: {
    };

}

export namespace Hadoop {
    const prototype: {
    };

}

export namespace Halt {
    const prototype: {
    };

}

export namespace Help {
    const prototype: {
    };

}

export namespace Heroku {
    const prototype: {
    };

}

export namespace History {
    const prototype: {
    };

}

export namespace Home {
    const prototype: {
    };

}

export namespace Horton {
    const prototype: {
    };

}

export namespace Host {
    const prototype: {
    };

}

export namespace HostMaintenance {
    const prototype: {
    };

}

export namespace Hp {
    const prototype: {
    };

}

export namespace Hpe {
    const prototype: {
    };

}

export namespace HpeLabs {
    const prototype: {
    };

}

export namespace Hpi {
    const prototype: {
    };

}

export namespace Html5 {
    const prototype: {
    };

}

export namespace IceCream {
    const prototype: {
    };

}

export namespace Image {
    const prototype: {
    };

}

export namespace Impact {
    const prototype: {
    };

}

export namespace InProgress {
    const prototype: {
    };

}

export namespace Inbox {
    const prototype: {
    };

}

export namespace Indicator {
    const prototype: {
    };

}

export namespace Info {
    const prototype: {
    };

}

export namespace Inherit {
    const prototype: {
    };

}

export namespace Inspect {
    const prototype: {
    };

}

export namespace Instagram {
    const prototype: {
    };

}

export namespace Install {
    const prototype: {
    };

}

export namespace InstallOption {
    const prototype: {
    };

}

export namespace Integration {
    const prototype: {
    };

}

export namespace InternetExplorer {
    const prototype: {
    };

}

export namespace Italic {
    const prototype: {
    };

}

export namespace Iteration {
    const prototype: {
    };

}

export namespace Java {
    const prototype: {
    };

}

export namespace Keyboard {
    const prototype: {
    };

}

export namespace Language {
    const prototype: {
    };

}

export namespace Launch {
    const prototype: {
    };

}

export namespace Layer {
    const prototype: {
    };

}

export namespace License {
    const prototype: {
    };

}

export namespace Like {
    const prototype: {
    };

}

export namespace LineChart {
    const prototype: {
    };

}

export namespace Link {
    const prototype: {
    };

}

export namespace LinkBottom {
    const prototype: {
    };

}

export namespace LinkDown {
    const prototype: {
    };

}

export namespace LinkNext {
    const prototype: {
    };

}

export namespace LinkPrevious {
    const prototype: {
    };

}

export namespace LinkTop {
    const prototype: {
    };

}

export namespace LinkUp {
    const prototype: {
    };

}

export namespace Linkedin {
    const prototype: {
    };

}

export namespace LinkedinOption {
    const prototype: {
    };

}

export namespace Local {
    const prototype: {
    };

}

export namespace Location {
    const prototype: {
    };

}

export namespace LocationPin {
    const prototype: {
    };

}

export namespace Lock {
    const prototype: {
    };

}

export namespace Login {
    const prototype: {
    };

}

export namespace Logout {
    const prototype: {
    };

}

export namespace Lounge {
    const prototype: {
    };

}

export namespace Magic {
    const prototype: {
    };

}

export namespace Mail {
    const prototype: {
    };

}

export namespace MailOption {
    const prototype: {
    };

}

export namespace Mandriva {
    const prototype: {
    };

}

export namespace Manual {
    const prototype: {
    };

}

export namespace Map {
    const prototype: {
    };

}

export namespace MapLocation {
    const prototype: {
    };

}

export namespace Mastercard {
    const prototype: {
    };

}

export namespace Medium {
    const prototype: {
    };

}

export namespace Menu {
    const prototype: {
    };

}

export namespace Microfocus {
    const prototype: {
    };

}

export namespace Microphone {
    const prototype: {
    };

}

export namespace Money {
    const prototype: {
    };

}

export namespace Monitor {
    const prototype: {
    };

}

export namespace Monospace {
    const prototype: {
    };

}

export namespace More {
    const prototype: {
    };

}

export namespace Multimedia {
    const prototype: {
    };

}

export namespace Multiple {
    const prototype: {
    };

}

export namespace Music {
    const prototype: {
    };

}

export namespace Mysql {
    const prototype: {
    };

}

export namespace Navigate {
    const prototype: {
    };

}

export namespace Network {
    const prototype: {
    };

}

export namespace New {
    const prototype: {
    };

}

export namespace NewWindow {
    const prototype: {
    };

}

export namespace Next {
    const prototype: {
    };

}

export namespace Nodes {
    const prototype: {
    };

}

export namespace Norton {
    const prototype: {
    };

}

export namespace Note {
    const prototype: {
    };

}

export namespace Notes {
    const prototype: {
    };

}

export namespace Notification {
    const prototype: {
    };

}

export namespace ObjectGroup {
    const prototype: {
    };

}

export namespace ObjectUngroup {
    const prototype: {
    };

}

export namespace OfflineStorage {
    const prototype: {
    };

}

export namespace Onedrive {
    const prototype: {
    };

}

export namespace Opera {
    const prototype: {
    };

}

export namespace Optimize {
    const prototype: {
    };

}

export namespace Oracle {
    const prototype: {
    };

}

export namespace OrderedList {
    const prototype: {
    };

}

export namespace Organization {
    const prototype: {
    };

}

export namespace Overview {
    const prototype: {
    };

}

export namespace Paint {
    const prototype: {
    };

}

export namespace Pan {
    const prototype: {
    };

}

export namespace Pause {
    const prototype: {
    };

}

export namespace PauseFill {
    const prototype: {
    };

}

export namespace Paypal {
    const prototype: {
    };

}

export namespace Performance {
    const prototype: {
    };

}

export namespace PersonalComputer {
    const prototype: {
    };

}

export namespace PieChart {
    const prototype: {
    };

}

export namespace PiedPiper {
    const prototype: {
    };

}

export namespace Pin {
    const prototype: {
    };

}

export namespace Pinterest {
    const prototype: {
    };

}

export namespace Plan {
    const prototype: {
    };

}

export namespace Play {
    const prototype: {
    };

}

export namespace PlayFill {
    const prototype: {
    };

}

export namespace Power {
    const prototype: {
    };

}

export namespace PowerCycle {
    const prototype: {
    };

}

export namespace PowerForceShutdown {
    const prototype: {
    };

}

export namespace PowerReset {
    const prototype: {
    };

}

export namespace PowerShutdown {
    const prototype: {
    };

}

export namespace Previous {
    const prototype: {
    };

}

export namespace Print {
    const prototype: {
    };

}

export namespace ProductHunt {
    const prototype: {
    };

}

export namespace Projects {
    const prototype: {
    };

}

export namespace Radial {
    const prototype: {
    };

}

export namespace RadialSelected {
    const prototype: {
    };

}

export namespace Raspberry {
    const prototype: {
    };

}

export namespace Reactjs {
    const prototype: {
    };

}

export namespace Reddit {
    const prototype: {
    };

}

export namespace Redhat {
    const prototype: {
    };

}

export namespace Redo {
    const prototype: {
    };

}

export namespace Refresh {
    const prototype: {
    };

}

export namespace Resources {
    const prototype: {
    };

}

export namespace Restaurant {
    const prototype: {
    };

}

export namespace Restroom {
    const prototype: {
    };

}

export namespace RestroomMen {
    const prototype: {
    };

}

export namespace RestroomWomen {
    const prototype: {
    };

}

export namespace Resume {
    const prototype: {
    };

}

export namespace Return {
    const prototype: {
    };

}

export namespace Revert {
    const prototype: {
    };

}

export namespace Rewind {
    const prototype: {
    };

}

export namespace Risk {
    const prototype: {
    };

}

export namespace Robot {
    const prototype: {
    };

}

export namespace RotateLeft {
    const prototype: {
    };

}

export namespace RotateRight {
    const prototype: {
    };

}

export namespace Rss {
    const prototype: {
    };

}

export namespace Run {
    const prototype: {
    };

}

export namespace SafariOption {
    const prototype: {
    };

}

export namespace Satellite {
    const prototype: {
    };

}

export namespace Save {
    const prototype: {
    };

}

export namespace Scan {
    const prototype: {
    };

}

export namespace Schedule {
    const prototype: {
    };

}

export namespace ScheduleNew {
    const prototype: {
    };

}

export namespace SchedulePlay {
    const prototype: {
    };

}

export namespace Schedules {
    const prototype: {
    };

}

export namespace Sco {
    const prototype: {
    };

}

export namespace Scorecard {
    const prototype: {
    };

}

export namespace Search {
    const prototype: {
    };

}

export namespace SearchAdvanced {
    const prototype: {
    };

}

export namespace Secure {
    const prototype: {
    };

}

export namespace Select {
    const prototype: {
    };

}

export namespace Selection {
    const prototype: {
    };

}

export namespace Semantics {
    const prototype: {
    };

}

export namespace Send {
    const prototype: {
    };

}

export namespace Server {
    const prototype: {
    };

}

export namespace ServerCluster {
    const prototype: {
    };

}

export namespace Servers {
    const prototype: {
    };

}

export namespace ServicePlay {
    const prototype: {
    };

}

export namespace Services {
    const prototype: {
    };

}

export namespace SettingsOption {
    const prototype: {
    };

}

export namespace Share {
    const prototype: {
    };

}

export namespace ShareOption {
    const prototype: {
    };

}

export namespace Shield {
    const prototype: {
    };

}

export namespace ShieldSecurity {
    const prototype: {
    };

}

export namespace Shift {
    const prototype: {
    };

}

export namespace Shop {
    const prototype: {
    };

}

export namespace Sidebar {
    const prototype: {
    };

}

export namespace Sign {
    const prototype: {
    };

}

export namespace Skype {
    const prototype: {
    };

}

export namespace Slack {
    const prototype: {
    };

}

export namespace Snapchat {
    const prototype: {
    };

}

export namespace Solaris {
    const prototype: {
    };

}

export namespace Sort {
    const prototype: {
    };

}

export namespace Spa {
    const prototype: {
    };

}

export namespace Split {
    const prototype: {
    };

}

export namespace Splits {
    const prototype: {
    };

}

export namespace Square {
    const prototype: {
    };

}

export namespace StackOverflow {
    const prototype: {
    };

}

export namespace Stakeholder {
    const prototype: {
    };

}

export namespace Star {
    const prototype: {
    };

}

export namespace StarHalf {
    const prototype: {
    };

}

export namespace StatusCritical {
    const prototype: {
    };

}

export namespace StatusCriticalSmall {
    const prototype: {
    };

}

export namespace StatusDisabled {
    const prototype: {
    };

}

export namespace StatusDisabledSmall {
    const prototype: {
    };

}

export namespace StatusGood {
    const prototype: {
    };

}

export namespace StatusGoodSmall {
    const prototype: {
    };

}

export namespace StatusInfo {
    const prototype: {
    };

}

export namespace StatusInfoSmall {
    const prototype: {
    };

}

export namespace StatusPlaceholder {
    const prototype: {
    };

}

export namespace StatusPlaceholderSmall {
    const prototype: {
    };

}

export namespace StatusUnknown {
    const prototype: {
    };

}

export namespace StatusUnknownSmall {
    const prototype: {
    };

}

export namespace StatusWarning {
    const prototype: {
    };

}

export namespace StatusWarningSmall {
    const prototype: {
    };

}

export namespace Steps {
    const prototype: {
    };

}

export namespace StepsOption {
    const prototype: {
    };

}

export namespace Stop {
    const prototype: {
    };

}

export namespace StopFill {
    const prototype: {
    };

}

export namespace Storage {
    const prototype: {
    };

}

export namespace StreetView {
    const prototype: {
    };

}

export namespace StrikeThrough {
    const prototype: {
    };

}

export namespace Stripe {
    const prototype: {
    };

}

export namespace Subscript {
    const prototype: {
    };

}

export namespace Subtract {
    const prototype: {
    };

}

export namespace SubtractCircle {
    const prototype: {
    };

}

export namespace Superscript {
    const prototype: {
    };

}

export namespace Support {
    const prototype: {
    };

}

export namespace Suse {
    const prototype: {
    };

}

export namespace Swift {
    const prototype: {
    };

}

export namespace Swim {
    const prototype: {
    };

}

export namespace Sync {
    const prototype: {
    };

}

export namespace System {
    const prototype: {
    };

}

export namespace Table {
    const prototype: {
    };

}

export namespace TableAdd {
    const prototype: {
    };

}

export namespace Tag {
    const prototype: {
    };

}

export namespace Tape {
    const prototype: {
    };

}

export namespace TapeOption {
    const prototype: {
    };

}

export namespace Target {
    const prototype: {
    };

}

export namespace Task {
    const prototype: {
    };

}

export namespace Tasks {
    const prototype: {
    };

}

export namespace Technology {
    const prototype: {
    };

}

export namespace Template {
    const prototype: {
    };

}

export namespace Terminal {
    const prototype: {
    };

}

export namespace Test {
    const prototype: {
    };

}

export namespace TestDesktop {
    const prototype: {
    };

}

export namespace TextAlignCenter {
    const prototype: {
    };

}

export namespace TextAlignFull {
    const prototype: {
    };

}

export namespace TextAlignLeft {
    const prototype: {
    };

}

export namespace TextAlignRight {
    const prototype: {
    };

}

export namespace TextWrap {
    const prototype: {
    };

}

export namespace Threats {
    const prototype: {
    };

}

export namespace ThreeD {
    const prototype: {
    };

}

export namespace ThreeDffects {
    const prototype: {
    };

}

export namespace Ticket {
    const prototype: {
    };

}

export namespace Tip {
    const prototype: {
    };

}

export namespace Toast {
    const prototype: {
    };

}

export namespace Tools {
    const prototype: {
    };

}

export namespace Tooltip {
    const prototype: {
    };

}

export namespace TopCorner {
    const prototype: {
    };

}

export namespace Train {
    const prototype: {
    };

}

export namespace Transaction {
    const prototype: {
    };

}

export namespace Trash {
    const prototype: {
    };

}

export namespace Tree {
    const prototype: {
    };

}

export namespace TreeOption {
    const prototype: {
    };

}

export namespace Trigger {
    const prototype: {
    };

}

export namespace Trophy {
    const prototype: {
    };

}

export namespace Troubleshoot {
    const prototype: {
    };

}

export namespace Tty {
    const prototype: {
    };

}

export namespace Tumblr {
    const prototype: {
    };

}

export namespace Turbolinux {
    const prototype: {
    };

}

export namespace Twitter {
    const prototype: {
    };

}

export namespace Ubuntu {
    const prototype: {
    };

}

export namespace Underline {
    const prototype: {
    };

}

export namespace Undo {
    const prototype: {
    };

}

export namespace Unlink {
    const prototype: {
    };

}

export namespace Unlock {
    const prototype: {
    };

}

export namespace UnorderedList {
    const prototype: {
    };

}

export namespace Up {
    const prototype: {
    };

}

export namespace Update {
    const prototype: {
    };

}

export namespace Upgrade {
    const prototype: {
    };

}

export namespace Upload {
    const prototype: {
    };

}

export namespace User {
    const prototype: {
    };

}

export namespace UserAdd {
    const prototype: {
    };

}

export namespace UserAdmin {
    const prototype: {
    };

}

export namespace UserExpert {
    const prototype: {
    };

}

export namespace UserFemale {
    const prototype: {
    };

}

export namespace UserManager {
    const prototype: {
    };

}

export namespace UserNew {
    const prototype: {
    };

}

export namespace UserPolice {
    const prototype: {
    };

}

export namespace UserSettings {
    const prototype: {
    };

}

export namespace UserWorker {
    const prototype: {
    };

}

export namespace Validate {
    const prototype: {
    };

}

export namespace Vend {
    const prototype: {
    };

}

export namespace Video {
    const prototype: {
    };

}

export namespace View {
    const prototype: {
    };

}

export namespace Vimeo {
    const prototype: {
    };

}

export namespace VirtualMachine {
    const prototype: {
    };

}

export namespace VirtualStorage {
    const prototype: {
    };

}

export namespace Visa {
    const prototype: {
    };

}

export namespace VmMaintenance {
    const prototype: {
    };

}

export namespace Vmware {
    const prototype: {
    };

}

export namespace Volume {
    const prototype: {
    };

}

export namespace VolumeControl {
    const prototype: {
    };

}

export namespace VolumeLow {
    const prototype: {
    };

}

export namespace VolumeMute {
    const prototype: {
    };

}

export namespace Vulnerability {
    const prototype: {
    };

}

export namespace Waypoint {
    const prototype: {
    };

}

export namespace Wheelchair {
    const prototype: {
    };

}

export namespace WheelchairActive {
    const prototype: {
    };

}

export namespace Wifi {
    const prototype: {
    };

}

export namespace WifiLow {
    const prototype: {
    };

}

export namespace WifiMedium {
    const prototype: {
    };

}

export namespace WifiNone {
    const prototype: {
    };

}

export namespace Windows {
    const prototype: {
    };

}

export namespace WindowsLegacy {
    const prototype: {
    };

}

export namespace Wordpress {
    const prototype: {
    };

}

export namespace Workshop {
    const prototype: {
    };

}

export namespace Yoga {
    const prototype: {
    };

}

export namespace Youtube {
    const prototype: {
    };

}

export namespace ZoomIn {
    const prototype: {
    };

}

export namespace ZoomOut {
    const prototype: {
    };

}

export namespace extendDefaultTheme {
    const prototype: {
    };

}

